#!/usr/bin/env python3
"""Compile gloss-swarm raw (spec 005 M2 ②) → the bundled overlay hanja-gloss-swarm/hanja_gloss.txt.

Reads `swarm-raw/gloss-*.json`, validates each (reading, hanja) against the canonical hanja.txt, and writes
`status=full` glosses as `읽기:한자:훈음`. This overlay is OUR data (MIT) — short standard 훈음 generated by an
LLM swarm — and (like the 004 overlays) fills EMPTY glosses only when merged. `status=wrong_reading` pairs are
REPORTED as tier-override candidates (reviewed by hand into tier-overrides.txt, never auto-applied). 미상 and
non-canonical entries are dropped.

Run:  python3 scripts/build_gloss_compile.py
"""

from __future__ import annotations

import glob
import json
from collections import defaultdict
from pathlib import Path

HANJA = "Sources/HanjaKitCore/Resources/hanja.txt"
RAW = "docs/specs/005-candidate-quality/swarm-raw"
OUT = "Sources/HanjaKitCore/Resources/data/hanja-gloss-swarm/hanja_gloss.txt"
HEADER = (
    "# HanjaKey swarm-found 훈음 overlay (spec 005 M2 ②): `읽기:한자:훈음`.\n"
    "# OUR data (MIT) — short standard 훈음 generated by an LLM swarm (scripts/build_gloss_*.py).\n"
    "# Fills EMPTY glosses only when merged by HanjaTable.bundled() + build_tiers.py, after the 004 sources."
)


def canonical() -> set[tuple[str, str]]:
    s: set[tuple[str, str]] = set()
    for line in open(HANJA, encoding="utf-8"):
        if line.startswith("#") or not line.strip():
            continue
        c = line.rstrip("\n").split(":", 2)
        if len(c) >= 2 and c[0] and c[1]:
            s.add((c[0], c[1]))
    return s


def main() -> int:
    canon = canonical()
    full: dict[tuple[str, str], str] = {}  # (reading, hanja) -> gloss (last wins)
    wrong: list[tuple[str, str]] = []
    counts: dict[str, int] = defaultdict(int)

    for fp in sorted(glob.glob(f"{RAW}/gloss-*.json")):
        d = json.load(open(fp, encoding="utf-8"))
        for e in d.get("result", d).get("combined", []):
            r, h = e.get("reading"), e.get("hanja")
            g = (e.get("gloss") or "").strip().replace("\n", " ")
            st = e.get("status", "")
            counts[st or "?"] += 1
            if (r, h) not in canon:
                counts["invalid_dropped"] += 1
                continue
            if st == "full" and g:
                full[(r, h)] = g
            elif st == "wrong_reading":
                wrong.append((r, h))

    Path(OUT).parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(HEADER + "\n")
        for r, h in sorted(full):
            f.write(f"{r}:{h}:{full[(r, h)]}\n")

    print(f"[ok] wrote {len(full)} full glosses -> {OUT}")
    print(f"[status] {dict(sorted(counts.items()))}")
    print(
        f"[wrong_reading] {len(wrong)} (review → tier-overrides.txt): {sorted(wrong)[:40]}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
